"""add_user_settings_preferences

Revision ID: 095ae973ba99
Revises: 9dd97ad6614b
Create Date: 2026-03-21 13:21:40.114579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '095ae973ba99'
down_revision = '9dd97ad6614b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('units', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('units')
        batch_op.drop_column('theme')

    # ### end Alembic commands ###
