"""add user admin and refinement fields

Revision ID: 9dd97ad6614b
Revises: bef33c90a7dc
Create Date: 2026-03-21 12:36:12.699572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dd97ad6614b'
down_revision = 'bef33c90a7dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('allows_admin_emails', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('profile_pic_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_pic_path')
        batch_op.drop_column('allows_admin_emails')
        batch_op.drop_column('is_approved')
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
